### ISSUE TITLE
Water Friends Plants

### ISSUE THREAD

**Issue by ethanbreck** [Voxel-Fox-Ltd/Flower#24]
A fun feature would be allowing people to water plants for other people in a server, if you know their plant name.

**Comment by 4Kaylum** [comment]
This is something I've debated with for a lil bit, honestly, but there's a lot to think about with a seemingly simple feature.

* When the plant is watered who gets the exp?
* When the plant is watered what cooldown does the plant get?
* When the plant is watered what happens to the multipliers?
* Should users be able to opt out of people watering their plants?

It's deceptively complex.

**Comment by ethanbreck** [comment]
There is a fair bit to think about with this feature. I am unsure if it should get implemented, I personally think its a good idea. My thoughts on it are the following based on the questions above: 

- The exp should be split 60 - 40 to whoever is watering it. Owner still gets exp cause its their plant, but whoever is keeping it alive gets more exp. 
- for the cooldown, maybe just have it done on a plant by plant basis similar to how it is regularly done, the same 15 minute cooldown regardless of who is watering it.
- I would think the multipliers should be the same on a plant by plant basis, so if I have voted, and have had it alive longer than a week, it would get the 1.1x and 1.2x multiplier. 
- For opting in or opting out, i would think it would be similar to plant sitting in real life, where you have to give a specific player permissions to water your plants, similar to giving them a key to your house to water your plants.

It is more complex than i would have thought when the idea popped into my head when talking to friends

**Comment by FailSpy** [comment]
Maybe the 'water cooldown' should be longer for someone who's trying to water someone else's plant -- that way the person can't easily grief you by watering before you get to it.
To clarify: 15 minutes has passed, owner can water. An hour has passed, someone else can water.

That way it's like your friends can act as a backstop from plants dying while you're not around to water.

Additionally or alternatively, maybe it's worth considering a friends system, where only friends can water it.
Maybe the original owner of a traded plant can also water it? That's a design choice for you.

To simplify your job, I would make it so a friend can water any plant you own.  (if you wanted a kind of reasonable context for it, it's giving them a spare key to your garden so they can access your plants.)

What would also be useful then is adding some way to see the available plants, considering now it's not just your plants. 
Either *all* available plants, or just a specific users. e.g. 
`/check @FailSpy`
`You check FailSpy's garden, and see these plants look a little dry: ...` 
(next watering will check against FailSpy's plants specifically? maybe?)
`/water failplant`
`You watered FailSpy's failplant! The crocus almost seems grateful.`

**Comment by 4Kaylum** [comment]
> Maybe the 'water cooldown' should be longer for someone who's trying to water someone else's plant

> Additionally or alternatively, maybe it's worth considering a friends system, where only friends can water it.

I like those ideas. I think that would make a good system and be a nice way to balance it out. It doesn't necessarily answer the exp question but these are a good way to start looking into solving things.

**Comment by FailSpy** [comment]
I'm personally quite for splitting the EXP between the owner and waterer.

So a useful way of figuring out the right balance is this: Say the point a friend can water it is every hour, and the split between waterer/owner XP is 80/20. Then the EXP gain is really only 25% of watering potential of your own plant, because you can only water once for every 4 times you could water your plant. 20% for the waterer, 5% for the owner.

In order to gain a full plant's worth for an hour as the waterer, you'd have to water 5 of your friends' plants. Halve the overall EXP: 10 plants. Double it: 3.

All depends on how worried you are about it being overpowered or it being too underpowered to bother.
And then there's room to add caps on EXP potential: a friend limit? a "travel time between gardens" limit? (e.g. can only water 4 people's gardens within an hour)

As far as *multipliers* go, I would treat the question of which multipliers apply as if the owner was watering that plant for any plant-based modifiers (e.g. kept alive a week), and apply the waterer's multipliers to it (e.g. voted for the bot).

For calculating it I'd say just calculate the total EXP as you normally would then split that total however you like.

And finally, I would propose some way of notifying the owner that their plant had been watered by a user and how much EXP they got -- most likely in the form of next time they use some command(s). 

"While you were away, 4Kaylum watered your plant __ times! You gained __ XP."

**Comment by 4Kaylum** [comment]
Now I've done the exp changes and put some basic monetization into Flower I'm putting this back at the top of the priority list of things to do. Just so you're aware.

**Comment by 4Kaylum** [comment]
This is now merged with FailSpy's keys system. I'll do a proper writeup of this later, adding it to Topgg and the README's commands list.

**Comment by ethanbreck** [comment]
Sounds good, thans for doing the stuff
