### ISSUE TITLE
Gifting subscriptions?

### ISSUE THREAD

**Issue by ghost** [Voxel-Fox-Ltd/Flower#60]
Would this be possible to implement?

**Comment by 4Kaylum** [comment]
What is it that you're looking to achieve? Permanently pay for someone else's subscription? Gift them a month so they don't have to pay for a single month of their ongoing subscription?

What exactly is it you're looking to achieve.

**Comment by cleverkooky** [comment]
I am interested in permanent subscriptions.

**Comment by 4Kaylum** [comment]
That seems like a different request than "gifting subscriptions" - could you fully explain what it is that you're looking for?

**Comment by cleverkooky** [comment]
Sorry for being unclear. I have a small server and would like to purchase a permanent subscription to enable premium functionality server-wide.

**Comment by 4Kaylum** [comment]
That's an interesting use case. Subscriptions are per-user, so a subscription for a whole server isn't something that greatly makes sense to implement, especially as user plants are also specific to them rather than to the server. 

If this WAS going to be something I implemented then it would require me to look into tracking where users run their commands so as to accurately work out how many users to charge you for.
